### ISSUE TITLE
Unable to set nickname

### ISSUE THREAD

**Issue by AfonsoHackers** [SkyCraft78/DiSky3#59] opened 2021-11-26 23:21 UTC
I just can't simply change anyone's nick name, I get no errors on console, syntax is correct, yet the nick name doesn't change. 
The bot has all the perms, the role is above mine, etc.

**Comment by wallace4BR** [comment] 2021-11-30 20:29
> 

Make sure you arent the guild owner cuz bot cant change it
i tried the reflect effect and it worked

**Comment by SkyCraft78** [comment] 2021-12-01 17:25
Tried from my side too, worked fine;
Could you send here the exact error you got please?

**Comment by AfonsoHackers** [comment] 2021-12-02 08:18
That’s the issue, I didn’t get one.

**Comment by SkyCraft78** [comment] 2021-12-02 09:49
Then this means that you are or the bot are unable to change nickname, because of permission of hierarchy of roles.

**Comment by AfonsoHackers** [comment] 2021-12-03 07:39
Shouldn’t the bot output an error if it couldn’t change my name? Also, his role is above mine.. and I am not the server owner.

**Comment by SkyCraft78** [comment] 2021-12-15 14:32
Did the bug still occur?
I am still unable to reproduce it, it works fine for me :/

**Comment by wallace4BR** [comment] 2021-12-22 20:27
I'm unable to reproduce that in some 3.7 version
![image](https://user-images.githubusercontent.com/81590228/147151400-de5e8daa-3b47-492b-a560-b3f422037663.png)
Code used:
```code
discord command change [<member>] [<text>]:
	trigger:
		reply with "Nick before: %nick name of arg-1%"
		set nickname of arg-1 to arg-2
		wait 1 second
		reply with "Nick now: %nick name of arg-1%"
```
Make sure you arent guild owner for that work, i'm closing it now

**Closed by wallace4BR** 2021-12-22 20:27 UTC
Labels: help wanted, question
